name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: repartease
    steps:
      - uses: actions/checkout@v3
      - name: Build Apps
        run: |
          npm install
          npm run build
      - name: Configure SSH
        env:
          KEY: ${{ secrets.KEY }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p /home/runner/.ssh
          echo "${KEY}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-keyscan $HOST >> /home/runner/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add /home/runner/.ssh/github_actions
      - name: Deploy to DigitalOcean Droplet
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
        run: |
          scp -r $USERNAME@$HOST:/repartease/frontend ./apps/frontend/dist
          scp -r $USERNAME@$HOST:/repartease/reverse-proxy ./apps/reverse-proxy/dist
          scp -r $USERNAME@$HOST:/repartease/server ./apps/server/dist
