name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: repartease
    steps:
      - uses: actions/checkout@v3
      - name: Build Apps
        run: |
          npm install
          npm run build
      - name: Deploy reverse-proxy DigitalOcean Droplet
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./apps/reverse-proxy/dist
          remote: /repartease/reverse-proxy
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_DROPLET_USERNAME }}
          password: ${{ secrets.DO_DROPLET_PASSWORD }}
      
